package com.ships.controllers;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;

import com.ships.services.OrderInfoService;
import com.ships.services.ShipService;
import com.ships.services.ShippingCompanyService;

@Controller    // This means that this class is a Controller
public class OrderController 
{
	
	@Autowired 	// This means to get the bean called orderService, Which is auto-generated by Spring, we will use it to handle the data
	private OrderInfoService orderService;
	
	@Autowired 	// This means to get the bean called shippingCompanyService, Which is auto-generated by Spring, we will use it to handle the data
	private ShippingCompanyService shippingCompanyService;
	
	@Autowired 	// This means to get the bean called shipService, Which is auto-generated by Spring, we will use it to handle the data
	private ShipService shipService;
}
