package com.ships.controllers;

import java.util.ArrayList;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import com.ships.model.Ship;
import com.ships.model.ShippingCompany;
import com.ships.services.ShipService;
import com.ships.services.ShippingCompanyService;

@Controller
public class ShippingCompanyController
{
	@Autowired // This means to get the bean called shipService, Which is auto-generated by Spring, we will use it to handle the data
	private ShippingCompanyService shippingCompanyService;
	
	@RequestMapping(value = "/showShippingCompanies", method = RequestMethod.GET)
	
	// Setup our method to display all ships in the 'ship' table
	public String getShippingCompanies(Model s)
	{
		ArrayList<ShippingCompany> shippingCompaniesList = shippingCompanyService.listAll();
		
		s.addAttribute("shippingCompaniesList", shippingCompaniesList);
		
		return "showShippingCompanies";
	}
	

}
