package com.ships.controllers;

import java.util.ArrayList;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import com.ships.model.Ship;
import com.ships.services.ShipService;

@Controller
public class ShipController 
{
	@Autowired // This means to get the bean called shipService, Which is auto-generated by Spring, we will use it to handle the data
	private ShipService shipService;
	
	@RequestMapping(value = "/showShips", method = RequestMethod.GET)
	
	// Setup our method to display all ships in the 'ship' table
	public String getShips(Model s)
	{
		ArrayList<Ship> shipList = shipService.listAll();
		
		s.addAttribute("shipList", shipList);
		
		return "showShips";
	}
	
}
